name: CI Actions Test

on:
  push:
    paths:
      - "src/a/b.version"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Prepare Preparing to test some commands.
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -al
          ls -al /
          ls -al /etc
          id 
          sudo id

      - name: Prepare a
        run: |
          # cp -fr src/cf/run.sh $PWD/run.sh && chmod +x run.sh && ./run.sh
          cp -fr src/cf/run.sh . && chmod +x run.sh && ./run.sh
          # sudo chmod -R 777 ./run.sh; sudo chown -R root:root ./run.sh
          # bash ./run.sh

      - name: Prepare z
        run: |
          mkdir -p $PWD/mymain; install -d $PWD/mymain
          WORKING_DIR="$PWD/mymain"
          echo $WORKING_DIR
          # https://github.com/cloudflare/cloudflared
          # https://hub.docker.com/r/cloudflare/cloudflared

          sudo docker run -itd \
            --name=cloudflared \
            --privileged \
            --cap-add=SYS_ADMIN --cap-add=NET_ADMIN --cap-add=NET_BIND_SERVICE \
            --network=host \
            --restart=always \
            -v $WORKING_DIR/dev/shm:$WORKING_DIR/dev/shm \
            cloudflare/cloudflared \
            tunnel --no-autoupdate --edge-ip-version auto --protocol auto run --token ${{ secrets.Argo_TOKEN }}

          cloudflared_images="$(docker images | grep cloudflared | awk 'NR==1 {print $1}')";if [ ${cloudflared_images} ]; then  echo "$(date +"%Y-%m-%d %H:%M:%S") === Successfully pulled cloudflared image."; else echo "$(date +"%Y-%m-%d %H:%M:%S") === Failed to pull cloudflared image."; fi
          docker logs xray
          docker logs caddy
          docker logs cloudflared
          sleep 5
          sudo docker restart cloudflared
          docker ps -as
          docker logs xray
          docker logs caddy
          docker logs cloudflared

      - name: Run Docker ps every 5 seconds for 30 minutes
        run: |
          INTERVAL=5
          TOTAL_TIME=1800  # 30 minutes in seconds
          START_TIME=$(date +%s)

          while true; do
              docker ps -as

              CURRENT_TIME=$(date +%s)
              ELAPSED_TIME=$((CURRENT_TIME - START_TIME))

              if [ "$ELAPSED_TIME" -ge "$TOTAL_TIME" ]; then
                  echo "Reached 30 minutes, stopping."
                  break
              fi

              sleep $INTERVAL
          done

      # - name: Pause for 30 minutes
      #   run: |
      #     sleep 5
      #     docker ps -as
      #     sleep 30m
