name: Daed

on:
  push:
    paths:
      - "src/daed/daed.version"
  workflow_dispatch:

jobs:
  build:
    name: Build - ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          # - { name: Windows x86, goos: windows, goarch: 386 }
          # - { name: Windows x86_64, goos: windows, goarch: amd64 }
          # - { name: Windows arm5, goos: windows, goarch: arm, goarm: 5 }
          # - { name: Windows arm6, goos: windows, goarch: arm, goarm: 6 }
          # - { name: Windows arm7, goos: windows, goarch: arm, goarm: 7 }
          # - { name: Windows arm64, goos: windows, goarch: arm64 }
          # - { name: Linux x86, goos: linux, goarch: 386 }
          # - { name: Linux x86_64, goos: linux, goarch: amd64 }
          # - { name: Linux arm5, goos: linux, goarch: arm, goarm: 5 }
          # - { name: Linux arm6, goos: linux, goarch: arm, goarm: 6 }
          # - { name: Linux arm7, goos: linux, goarch: arm, goarm: 7 }
          # - { name: Linux arm64, goos: linux, goarch: arm64 }
          - { name: Daed, target: frontend }
          - { name: Dae-wing, target: backend }
    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout daed repo
        uses: actions/checkout@v4
        with:
          repository: daeuniverse/daed-revived-next
          path: daed
          submodules: 'recursive'

      # - name: Checkout daed repo
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      #   run: |
      #     git clone https://github.com/daeuniverse/daed-revived-next.git
      #     # gh repo clone daeuniverse/daed-revived-next

      # - name: Copy daed repo
      #   run: |
      #     # cp -fr daed/* $PWD
      #     cp -fr daed/* .
      #     ls -al

      - name: Setup Variables
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          # CONTENT_PATH: "src/daed/daed.version"
        run: |
          echo "GO_VERSION=$(wget -qO- https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | jq -r .[0].version)" >> $GITHUB_ENV
          echo "GO_VERSION: $(curl -sL https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | jq -r '.[0].version')"
          echo "CURRENT_PATH=$PWD" >> $GITHUB_ENV
          echo "CURRENT_PATH: $PWD"

      - name: Initialize daed repo
        run: |
          cd $CURRENT_PATH/daed
          ls -al
          git submodule update --init --recursive
          # sed -i 's|FROM docker.io/node.*|FROM node:slim AS base|g' Dockerfile
          sed -i 's|FROM docker.io/node.*|FROM node:alpine AS base|g' Dockerfile
          cat Dockerfile
          
          # cat <<EOF> .env.local
          # WING_API_URL=http://10.18.27.27:2023
          # HOSTNAME=0.0.0.0
          # PORT=3000
          
          # EOF
          # ls -al
          # echo "233255"
          # cat .env.local

      - name: Modify daed repo
        if: matrix.config.target == 'backend'
        run: |
          cd $CURRENT_PATH/daed/wing
          ls -al
          sed -i '/^RUN make APPNAME=dae*/i RUN go mod tidy' Dockerfile
          cat Dockerfile

      # https://docs.docker.com/build/ci/github-actions/push-multi-registries/
      # https://github.com/daeuniverse/daed/discussions/291
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push - ${{ matrix.config.name }}
        if: matrix.config.target == 'frontend'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CURRENT_PATH }}/daed
          # file: Dockerfile
          provenance: false
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/daed:latest
      - name: Build and push - ${{ matrix.config.name }}
        if: matrix.config.target == 'backend'
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CURRENT_PATH }}/daed/wing
          # file: Dockerfile
          provenance: false
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dae-wing:latest
