name: AutoCheck

on:
  workflow_dispatch:

jobs:
  autocheck:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          mkdir -p path\to\ready
          echo hello > path\to\ready\world0.txt
          echo hello > path\to\ready\world1.txt
          echo hello > path\to\ready\world2.txt

      - name: Upload to GitHub Release for all platform
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          CONTENT_PATH: ".github/haproxy.version"
        run: |
          TARGET_TAG="haproxy"
          if [[ "$(gh api repos/{owner}/{repo}/tags --jq '.[].name')" = "${TARGET_TAG}" ]]; then
          gh release upload "${TARGET_TAG}" (Get-Item .\path\to\ready\* -Force) --clobber
          else
          gh release create "${TARGET_TAG}" (Get-Item .\path\to\ready\* -Force) --title "Haproxy Rolling Release" \
          --notes "Haproxy Version: <code>[${{ env.CONTENT_PATH }}](https://github.com/haproxy/haproxy/releases/tag/${{ env.CONTENT_PATH }})</code><br><br>**These are automatically updated builds of the latest commit.**"
          fi
