name: DemoTest

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest
    steps:
      # - run: git config --global core.autocrlf input
      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: Configure Makefile
        shell: pwsh
        run: |
          (ls env:Path).Value -split ";"
      - name: Configure Makefile
        shell: bash
        run: |
          echo 233
          echo 255
          uname -a
          pwd
          ls -al
