name: DemoTest

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest

    # defaults:
    #   run:
    #     shell: msys2 {0}

    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            coreutils
            curl
            wget
            diffutils
            git
            gawk
            gcc
            gdb
            make
            tar
            zip
            openssl
            openssl-devel
            pcre-devel
            pcre2-devel
            zlib-devel
      - name: Compile CI-Build
        shell: msys2 {0}
        run: |
          echo 'Running in MSYS2!'
          gcc --version
          g++ --version
          gdb --version
          make --version
          curl -R -O http://www.lua.org/ftp/lua-5.4.6.tar.gz
          tar zxvf lua-5.4.6.tar.gz
          ls -al
          cd lua-5.4.6
          ls -al
          make mingw all
          # make -j$(nproc) mingw all
          ./src/lua -v
