name: AutoCheck

on:
  workflow_dispatch:

env:
  REGISTRY_IMAGE: darkommoers/wireguard

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,enable=true,value=main
            type=raw,enable=true,value=root

      - name: Test
        run: |
          for i in $(echo $DOCKER_METADATA_OUTPUT_TAGS | xargs); do
            echo "Inspect images: $i"
          done
