name: DemoTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout self
        uses: actions/checkout@v4
      - run: |
          pwd
          ls -al
      - name: Checkout haproxy
        uses: actions/checkout@v4
        with:
          repository: haproxy/haproxy
          path: haproxy
      - run: |
          pwd
          ls -al
      - name: Check the haproxy repo
        working-directory: haproxy
        run: |
          pwd
          cat VERSION
          ls -la
