name: DemoTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          # msystem: MINGW64
          # update: true
          install: coreutils diffutils gcc gdb make openssl-devel pcre-devel pcre2-devel zlib-devel curl wget zip git
          # install: >-
          #   git
          #   curl
          #   wget
      - name: Configure Compile Lua
        shell: msys2 {0}
        run: |
          curl -R -O http://www.lua.org/ftp/lua-5.4.6.tar.gz
          tar zxf lua-5.4.6.tar.gz
          cd lua-5.4.6
          make all test
          echo "Show lua version"
          src/lua -v
          src/luac -v
