name: DemoTest

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest

    # defaults:
    #   run:
    #     shell: msys2 {0}

    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            coreutils
            curl
            diffutils
            gawk
            gcc
            make
            tar
            openssl-devel
            pcre-devel
            zlib-devel
      - name: Configure Compile Lua
        shell: msys2 {0}
        run: |
          latest_luaname=$(curl -sL https://www.lua.org/ftp/ | grep -oP 'lua-[0-9](.*?).tar.gz' | uniq | sed -n '1p')
          curl -R -O https://www.lua.org/ftp/${latest_luaname}
          tar zxvf ${latest_luaname}
          current_luapathname=$(echo ${latest_luaname} | grep -oP '(.*?)(?=.tar.*$)')
          # current_luapathname=$(find ${PWD} -name "lua*" -type d | awk -F "/" '{print $NF}')
          echo "${latest_luaname} ${current_luapathname}"
          cd ${current_luapathname} || exit 2
          make -j$(nproc) mingw all
          # make INSTALL_TOP=/opt/${current_luapathname} install
          # make INSTALL_TOP=/opt/${current_luapathname} uninstall
          # make -j$(nproc) INSTALL_TOP=/opt/${current_luapathname} mingw install
          echo "Show lua version"
          src/lua -v
          src/luac -v
