name: AutoCheck

on:
  workflow_dispatch:

jobs:
  autocheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world0.txt

      - run: echo hello > path/to/artifact/world1.txt

      - run: echo hello > path/to/artifact/world2.txt

      - name: Upload to GitHub Release for all platform
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          TARGET_TAG="chisel"
          if [[ "$(gh api repos/{owner}/{repo}/tags --jq '.[].name')" = "${TARGET_TAG}" ]]; then
          gh release upload "${TARGET_TAG}" path/to/artifact/* --clobber
          else
          gh release create "${TARGET_TAG}" path/to/artifact/* --title "Chisel Rolling Release" \
          --notes "Chisel Version: <code>[v1.9.1](https://github.com/jpillora/chisel/releases/tag/v1.9.1)</code><br><br>**These are automatically updated builds of the latest commit.**"
          fi
