name: AutoCheck

on:
  workflow_dispatch:

env:
  REGISTRY_IMAGE: darkommoers/wireguard

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,enable=true,value=main
            type=raw,enable=true,value=root

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}

      - name: Test
        run: |
          for i in ${{ steps.meta.outputs.version }}; do 
          echo "${i}"
          done
          cat << EOF >  metadata.json
          ${{ steps.meta.outputs.json }}
          EOF
          cat metadata.json
          echo ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          echo ${{ fromJSON(steps.meta.outputs.json).tags[1] }}
