name: DemoTest

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest
    steps:
      # - run: git config --global core.autocrlf input
      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: Configure Makefile
        shell: C:\Program Files\Git\bin\bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
        run: |
          uname -a
          pwd
          ls -al
