name: DemoTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          # msystem: MINGW64
          # update: true
          install: coreutils diffutils gcc gdb make openssl-devel pcre-devel pcre2-devel zlib-devel curl wget zip git
          # install: >-
          #   git
          #   curl
          #   wget
          
      - name: Compile CI-Build
        shell: msys2 {0}
        run: |
          echo 'Running in MSYS2!'
          curl -R -O http://www.lua.org/ftp/lua-5.4.6.tar.gz
          tar zxvf lua-5.4.6.tar.gz
          ls -al
          cd lua-5.4.6
          ls -al
          make -j$(nproc) mingw all
          echo "Show lua version"
          ./src/lua -v
          echo "Show lua version"

      - name: Configure Compile Haproxy
        shell: msys2 {0}
        run: |
          echo ${current_luapathname}
          # git clone https://github.com/haproxy/haproxy.git
          # cd haproxy || exit 2
          # make -j$(nproc) all \
          #   ERR=1 \
          #   TARGET=cygwin \
          #   CC=gcc \
          #   DEBUG="-DDEBUG_STRICT -DDEBUG_MEMORY_POOLS -DDEBUG_POOL_INTEGRITY" \
          #   USE_LUA=1 LUA_LIB_NAME=lua LUA_INC=~/${current_luapathname}/src LUA_LIB=~/${current_luapathname}/src \
          #   USE_GETADDRINFO=1 USE_OPENSSL=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_THREAD=1 USE_ZLIB=1
          # make clean
          # make install
          # make uninstall
