name: DemoTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout self
        uses: actions/checkout@v4

      - name: test
        run: |
          TARGET_HTTP_CODE=404
          echo -e "\e[30;48;5;9m Hello\e[0m"
          echo -e "\e[30;48;5;10m Hello\e[0m"
          echo -e "\e[30;48;5;11m Hello\e[0m"
          echo -e "\e[30;48;5;12m Hello\e[0m"
          echo -e "\e[30;48;5;13m Hello\e[0m"
          echo -e "\e[30;48;5;14m Hello\e[0m"
          echo -e "\e[30;48;5;15m Hello\e[0m"
          
          echo -e "\e[21;48;5;9m Hello\e[0m"
          echo -e "\e[21;48;5;10m Hello\e[0m"
          echo -e "\e[21;48;5;11m Hello\e[0m"
          echo -e "\e[21;48;5;12m Hello\e[0m"
          echo -e "\e[21;48;5;13m Hello\e[0m"
          echo -e "\e[21;48;5;14m Hello\e[0m"
          echo -e "\e[21;48;5;15m Hello\e[0m"
          
          echo -e "\033[1;40;96m$(date '+%F %T') === Fail: \033[0m\e[7;47;91m${TARGET_HTTP_CODE}\e[0m"
          echo -e "\033[1;40;91m$(date '+%F %T') === No target tag or release found, skip delete. \033[0m"
          
          echo -e "\033[1;40;92m$(date '+%F %T') === Success: \033[0m\e[7;47;96m${TARGET_HTTP_CODE}\e[0m"
          echo -e "\033[1;40;94m$(date '+%F %T') === Target tag or release \e[7;47;96m${TARGET_TAG}\e[0m\033[1;40;94m deleted Complete! \033[0m"
