name: DemoTest

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86_64
          # packages: make gcc-core gcc-g++
          packages: coreutils openssl-devel
          
      - name: Single-line inline shell
        run: echo "Running in $(pwd)"
        shell: C:\cygwin\bin\bash.exe '{0}'
  
      - name: Multiline inline shell
        run: >-
          echo "Running in $(pwd)" &&
          true
        shell: C:\cygwin\bin\bash.exe '{0}'
