name: DemoTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout haproxy repo
        uses: actions/checkout@v4
        with:
          repository: haproxy/haproxy
          path: haproxy

      - name: Add path
        run: |
          echo "C:\msys64\usr\bin" >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: |
          pacman -Q
