name: DemoTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout haproxy repo
        uses: actions/checkout@v4
        with:
          repository: haproxy/haproxy
          path: haproxy

      - name: test gh
        run: |
          $EnumColors = [Enum]::GetValues([ConsoleColor])
          Write-Host "$((Get-Date -UFormat "%F %T")) === Installing Hysteria Run" -ForegroundColor (Get-Random -InputObject $EnumColors)
          gh --version
          # Remove-Item alias:curl -Force -Recurse | Out-Null
