name: AutoCheck

on:
  workflow_dispatch:

jobs:
  autocheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Automatic check and push version
        env:
          # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          CONTENT_PATH: "src/caddy/caddy.version"
        uses: actions/github-script@v6
        with:
          github-token: ${{ env.GH_TOKEN }}
          script: |
            let current_caddy;
            let latest_caddy;
            let arrdate = () => {
              let date = new Date();
              let curTime = `${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()} ${date.getHours().toString().padStart(2,"0")}:${date.getMinutes().toString().padStart(2,"0")}:${date.getSeconds().toString().padStart(2,"0")} ${date.getDay()}`;
              return curTime;
            }
          
            let result_sha = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: `"/src/haproxy/haproxy.version"`
            })
            console.log(arrdate(),result_sha)
            console.log(arrdate(),result_sha.data.sha)
            console.log(arrdate(),result_sha.data.content)
            console.log(arrdate(),atob(result_sha.data.content).replace(/[\r\n]/g,""))
          
