name: AutoCheck

on:
  workflow_dispatch:

jobs:
  autocheck:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world0.txt

      - run: echo hello > path/to/artifact/world1.txt

      - run: echo hello > path/to/artifact/world2.txt
      
      - name: Upload to GitHub Release for all platform Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create release ./path/to/artifact/* -t "Rolling Release" -n "bugfix release"
          # gh release create release ./path/to/artifact/* --title "Rolling Release" --notes "bugfix release"
