name: DemoTest

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout haproxy repo
        uses: actions/checkout@v4
        with:
          repository: nginx/nginx
          path: nginx

      - name: Get source
        run: |
          echo run
          $clfileto="$Env:ProgramFiles\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\$((Get-ChildItem -Path "$Env:ProgramFiles\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\" -Recurse -Name cl.exe)[0])"
          $clfileto | foreach-object { "{0}`t{1}" -f $_.Name, [System.Diagnostics.FileVersionInfo]::GetVersionInfo($_).FileVersion } |% {$_ -match '\d{2}.\d{2}'};$clfilever=$Matches[0];$clfilever
          $newContent = switch -Wildcard -Regex -File .\nginx\auto\cc\msvc {
              'version:.*$' {
                  "NGX_MSVC_VER=${clfilever}"
                  $_
              }
              default { $_ }
          }
          $newContent | Set-Content .\nginx\auto\cc\msvc
          echo end

      - name: Configure Makefile
        shell: bash
        # shell: bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
        # shell: C:\msys64\usr\bin\bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
        run: |
          uname -a
          pwd
          ls -al
          cd nginx
          CUR=$PWD
          pwd
          ls -al
          curl -LJRO https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.42/pcre2-10.42.tar.gz
          curl -LJRO http://zlib.net/zlib-1.3.tar.gz
          curl -LJRO https://www.openssl.org/source/openssl-3.0.11.tar.gz
          mkdir -p objs/lib
          install -d objs/lib
          cd objs/lib
          tar -zxvf ../../pcre2-10.42.tar.gz
          tar -zxvf ../../zlib-1.3.tar.gz
          tar -zxvf ../../openssl-3.0.11.tar.gz
          pwd
          # cd ..
          # pwd
          # cd ..
          # pwd
          cd $CUR
          pwd
          ls -al
          # ./configure \
          auto/configure \
              --with-cc=cl \
              --with-debug \
              --prefix= \
              --conf-path=conf/nginx.conf \
              --pid-path=logs/nginx.pid \
              --http-log-path=logs/access.log \
              --error-log-path=logs/error.log \
              --sbin-path=nginx.exe \
              --http-client-body-temp-path=temp/client_body_temp \
              --http-proxy-temp-path=temp/proxy_temp \
              --http-fastcgi-temp-path=temp/fastcgi_temp \
              --http-scgi-temp-path=temp/scgi_temp \
              --http-uwsgi-temp-path=temp/uwsgi_temp \
              --with-cc-opt=-DFD_SETSIZE=1024 \
              --with-pcre=objs/lib/pcre2-10.42 \
              --with-zlib=objs/lib/zlib-1.3 \
              --with-http_v2_module \
              --with-http_realip_module \
              --with-http_addition_module \
              --with-http_sub_module \
              --with-http_dav_module \
              --with-http_stub_status_module \
              --with-http_flv_module \
              --with-http_mp4_module \
              --with-http_gunzip_module \
              --with-http_gzip_static_module \
              --with-http_auth_request_module \
              --with-http_random_index_module \
              --with-http_secure_link_module \
              --with-http_slice_module \
              --with-mail \
              --with-stream \
              --with-stream_realip_module \
              --with-stream_ssl_preread_module \
              --with-openssl=objs/lib/openssl-3.0.11 \
              --with-openssl-opt='no-asm no-tests -D_WIN32_WINNT=0x0501' \
              --with-http_ssl_module \
              --with-mail_ssl_module \
              --with-stream_ssl_module \
              --with-compat
